// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArXZ3r-yKWyOJsFlZd44ozvEAMHk4TWgw',
    appId: '1:99459481755:web:227daa8466d9440828463e',
    messagingSenderId: '99459481755',
    projectId: 'todo-webapp1',
    authDomain: 'todo-webapp1.firebaseapp.com',
    storageBucket: 'todo-webapp1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmg-_156pSRjn9lFfEl0A-8peN7koBgM8',
    appId: '1:99459481755:android:450a67993c2fbde128463e',
    messagingSenderId: '99459481755',
    projectId: 'todo-webapp1',
    storageBucket: 'todo-webapp1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN09tpuU5z16vlxkWdz52yFP-7Yh16IEI',
    appId: '1:99459481755:ios:27961dfe179128e528463e',
    messagingSenderId: '99459481755',
    projectId: 'todo-webapp1',
    storageBucket: 'todo-webapp1.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutterApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN09tpuU5z16vlxkWdz52yFP-7Yh16IEI',
    appId: '1:99459481755:ios:27961dfe179128e528463e',
    messagingSenderId: '99459481755',
    projectId: 'todo-webapp1',
    storageBucket: 'todo-webapp1.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutterApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArXZ3r-yKWyOJsFlZd44ozvEAMHk4TWgw',
    appId: '1:99459481755:web:dce88a485ed7d06e28463e',
    messagingSenderId: '99459481755',
    projectId: 'todo-webapp1',
    authDomain: 'todo-webapp1.firebaseapp.com',
    storageBucket: 'todo-webapp1.firebasestorage.app',
  );
}
